In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

In [11]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [12]:
mean_a = (a.mean(axis=0))

In [13]:
mean_a

array([2. , 8.4])

In [15]:
a_centered = np.subtract(a, mean_a)

In [16]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [25]:
a_centered_1 = a_centered[0:5,0]

In [26]:
a_centered_1

array([-1.,  0.,  1.,  1., -1.])

In [27]:
a_centered_2 = a_centered[0:5, 1]

In [28]:
a_centered_2 

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [29]:
a_centered_sp = np.dot(a_centered_1, a_centered_2)

In [30]:
a_centered_sp

8.0

In [31]:
a_centered_sp2 = a_centered_1.dot(a_centered_2)

In [32]:
a_centered_sp2

8.0